#!/bin/bash

echo "🚀 TESTING MENU FRAGMENT FORCE CLOSE FIX"
echo "========================================"
echo ""

echo "📱 Aplikasi sudah terinstall!"
echo ""
echo "🧪 STEPS TO TEST:"
echo "1. Buka aplikasi AdminWafeOfFood di emulator/device"
echo "2. Login dengan akun admin (aldo@gmail.com / password123)"  
echo "3. Tap tab 'Menu' di bottom navigation"
echo "4. Perhatikan apakah:"
echo "   ✅ Fragment berhasil load dengan text sederhana"
echo "   ❌ Aplikasi masih force close"
echo ""
echo "🔍 EXPECTED RESULT:"
echo "- Jika fragment minimal ini BEKERJA = masalah ada di kompleksitas kode MenuFragment original"
echo "- Jika fragment minimal ini CRASH = masalah ada di sistem/import/dependency"
echo ""
echo "📋 NEXT STEPS:"
echo "- Jika minimal works: kita akan perbaiki MenuFragment original step by step"  
echo "- Jika minimal crash: kita akan cek dependency dan import"
echo ""
echo "👆 Silahkan test aplikasi sekarang dan beri tahu hasilnya!"
